### ISSUE TITLE
Missing sp_l data in MMFIT

### ISSUE THREAD

**Issue by aqibsaeed** [KDMStromback/mm-fit#2]
Hi,

Thanks for open sourcing the dataset. I noticed that the sp_l_acc, sp_l_gyr and sp_l_mag are missing in MMFIT zip file but it is referenced in the code. Did you use it for training and evaluation? and what are the number of classes, the default value is None in utils.py. 

Thanks in advance.

**Comment by KDMStromback** [comment]
Thank you for your interest in our work.


Not all workout sessions were recorded using all sensors. sp_l (Smartphone Left) data exists only for a subset of workout sessions (w03, w06, w08, w13, w14, w17).

The starter code in this repo is setup to only train on a subset of all the available modalities in MM-Fit [(link):](https://github.com/KDMStromback/mm-fit/blob/e4b6b7e1fff68e3d93130ed087d23593c9016c94/train_multimodal_ar.py#L39).

``` python
MODALITIES_SUBSET = ['sw_l_acc', 'sw_l_gyr', 'sw_r_acc', 'sw_r_gyr', 'sp_r_acc', 'sp_r_gyr', 'eb_l_acc', 'eb_l_gyr', 'pose_3d']`
```
This can be modified to train on all modalities or different subsets.

MM-Fit contains 10 activity classes and the non-activity class, so in total there are 11 classes [(link):](https://github.com/KDMStromback/mm-fit/blob/e4b6b7e1fff68e3d93130ed087d23593c9016c94/utils/dataset.py#L32)

``` python
self.ACTIONS = {'squats': 0, 'lunges': 1, 'bicep_curls': 2, 'situps': 3, 'pushups': 4, 'tricep_extensions': 5,
                        'dumbbell_rows': 6, 'jumping_jacks': 7, 'dumbbell_shoulder_press': 8,
                        'lateral_shoulder_raises': 9, 'non_activity': 10}
``` 

To train a multimodal network for activity recognition using MM-Fit you can run the following command:

`python train_multimodal_ar.py --data "mm-fit/" --num_classes 11 --lr 0.001 --epochs 25 --batch_size 128 --ae_layers 3 --ae_hidden_units 1000 --embedding_units 1000 --ae_dropout 0.0 --window_length 5 --window_stride 0.2 --layers 3 --hidden_units 100 --dropout 0.0`


Let me know if you have any other questions.

**Comment by aqibsaeed** [comment]
Awesome! Thanks.
