### ISSUE TITLE
About the installation of the environment

### ISSUE THREAD

**Issue by crapper** [KDMStromback/mm-fit#3]
Excuse me, I'm currently tried to follow the readme and download the MM-fit data zip file and found there all of numpy files instead of videos, and when I follow the instruction and tried to install the environment, the following error pops out. I don't think there have so many package is invaild so I think I am missing something important, can I get any help? Thank you.
![image](https://user-images.githubusercontent.com/26902835/186159322-82e3ca09-7b03-4621-8e3c-e6b9c18fab62.png)

**Comment by KDMStromback** [comment]
Hi, thank you for your interest in the MM-Fit dataset. 

Unfortunately we have not been able to release the RGB+D data as we had planned to, and I can't provide a reliable estimate for when it could be expected. I hope that the other modalities in the dataset might still be of some use to you.

Regarding conda environment installation, please try with the below minimal environment file:

```
name: mm-fit
channels:
  - defaults
dependencies:
  - python=3.7
  - tqdm
  - torchvision
  - cudatoolkit=11.3
  - pytorch
  - pandas
  - scipy
  - jupyter
```
