### ISSUE TITLE
RGB data

### ISSUE THREAD

**Issue by nadav-eshel** [KDMStromback/mm-fit#4]
Hi. Is there anyway to get the actual RGB (or RGB+D) images that match with the sensor data and skeletons?
It's not in the dataset zip I downloaded from MM-Fit website.

Thank you
:)

**Comment by KDMStromback** [comment]
Hi, thank you for your interest in the MM-Fit dataset! Unfortunately we have not been able to release the RGB+D data as we had planned to, and I can't provide a reliable estimate for when it could be expected. I hope that the other modalities in the dataset might still be of some use to you.

**Comment by nadav-eshel** [comment]
Thank you for your response.
